---
deployment:
  tasks:
    - /bin/mkdir -p /home/fabricae/bfninecamisetas.com.br/mentov1
    - /bin/chmod 755 /home/fabricae/bfninecamisetas.com.br/mentov1
    - /bin/cp -rf index.html assets /home/fabricae/bfninecamisetas.com.br/mentov1/
    - /bin/chmod -R 755 /home/fabricae/bfninecamisetas.com.br/mentov1/assets 2>/dev/null || true
    - /bin/chmod 644 /home/fabricae/bfninecamisetas.com.br/mentov1/*.html 2>/dev/null || true
